import React from 'react';
import Head from 'next/head';

const Privacy = () => {
  return (
    <div>
      <Head>
        <title>Privacy Policy</title>
        <meta name="description" content="Terms and Conditions for using our website and services." />
      </Head>
      <main style={{ padding: '20px', fontFamily: 'Arial, sans-serif' }}>
        <h1 style={{ marginBottom: '20px', fontWeight: 'bold' }}>Privacy Policy</h1>

        <p style={{ marginBottom: '15px', lineHeight: '2' }}>
        Effective date: 2024-05-25
        <br />
          <span style={{ fontWeight: 'bold', textDecoration: 'underline' }}>1. Introduction</span>
          <br />
          Andrea Ricci (Andrea Ricci, “us”, “we”, or “our”) operates makethatmeme.com (hereinafter referred to as “Service”).
          <br />
          Our Privacy Policy governs your visit to makethatmeme.com, and explains how we collect, safeguard and disclose information that results from your use of our Service.
          <br />
          We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms of Service.
          <br />
          Our <a href="/terms" style={{ textDecoration: 'underline' }}>Terms and Conditions</a> (“Terms”) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (“agreement”).
        </p>

        <p style={{ marginBottom: '15px', lineHeight: '2' }}>
          <span style={{ fontWeight: 'bold', textDecoration: 'underline' }}>2. Definitions</span>
          <br />
          <strong>SERVICE</strong> means the makethatmeme.com website operated by Andrea Ricci.
          <br />
          <strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
          <br />
          <strong>USAGE DATA </strong>is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).
          <br />
          <strong>COOKIES</strong> are small files stored on your device (computer or mobile device).
          <br />
          <strong>DATA CONTROLLER</strong> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.
          <br />
          <strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.
          <br />
          <strong>DATA SUBJECT</strong> is any living individual who is the subject of Personal Data.
          <br />
          <strong>THE USER</strong> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
        </p>

        <p style={{ marginBottom: '15px', lineHeight: '2' }}>
          <span style={{ fontWeight: 'bold', textDecoration: 'underline' }}>3. Information Collection and Use</span>
          <br />
          We collect several different types of information for various purposes to provide and improve our Service to you.
        </p>

        <p style={{ marginBottom: '15px', lineHeight: '2' }}>
          <span style={{ fontWeight: 'bold', textDecoration: 'underline' }}>4. Types of Data Collected</span>
          <br />
          <span style={{ fontWeight: 'bold' }}>Personal Data</span>
          <br />
          While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”).
          Personally identifiable information may include, but is not limited to:
        </p>
        <ul style={{ marginBottom: '15px', listStyleType: 'disc', paddingLeft: '20px' }}>
          <li style={{ marginBottom: '10px' }}>Email address</li>
        </ul>
        <p style={{ marginBottom: '15px', lineHeight: '2' }}>
          We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or by emailing at info@makethatmeme.com
          <br />
          <span style={{ fontWeight: 'bold' }}>Usage Data</span>
          <br />
          We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through a mobile device (“Usage Data”).
          <br />
          This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          <br />
          When you access Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
        </p>

        <p style={{ marginBottom: '15px', lineHeight: '2' }}>
          <span style={{ fontWeight: 'bold', textDecoration: 'underline' }}>5. Use of Data</span>
          <br />
          Makethatmeme.com uses the collected data for various purposes:
        </p>
        <ul style={{ marginBottom: '15px', listStyleType: 'disc', paddingLeft: '20px' }}>
          <li style={{ marginBottom: '10px' }}>to provide and maintain our Service;</li>
          <li style={{ marginBottom: '10px' }}>to notify you about changes to our Service;</li>
          <li style={{ marginBottom: '10px' }}>to provide customer support;</li>
          <li style={{ marginBottom: '10px' }}>to gather analysis or valuable information so that we can improve our Service;</li>
          <li style={{ marginBottom: '10px' }}>to monitor the usage of our Service;</li>
          <li style={{ marginBottom: '10px' }}>to detect, prevent and address technical issues;</li>
          <li style={{ marginBottom: '10px' }}>to fulfill any other purpose for which you provide it;</li>
          <li style={{ marginBottom: '10px' }}>to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</li>
          <li style={{ marginBottom: '10px' }}>to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</li>
          <li style={{ marginBottom: '10px' }}>to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</li>
          <li style={{ marginBottom: '10px' }}>in any other way we may describe when you provide the information;</li>
          <li style={{ marginBottom: '10px' }}>for any other purpose with your consent.</li>
        </ul>

        <p style={{ marginBottom: '15px', lineHeight: '2' }}>
          <span style={{ fontWeight: 'bold', textDecoration: 'underline' }}>6. Retention of Data</span>
          <br />
          We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
          <br />
          We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
        </p>

        <p style={{ marginBottom: '15px', lineHeight: '2' }}>
          <span style={{ fontWeight: 'bold', textDecoration: 'underline' }}>7. Transfer of Data</span>
          <br />
          Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
          <br />
          If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.
          <br />
          Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
          <br />
          Makethatmeme.com will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.
        </p>

        <p style={{ marginBottom: '15px', lineHeight: '2' }}>
          <span style={{ fontWeight: 'bold', textDecoration: 'underline' }}>8. Disclosure of Data</span>
          <br />
          We may disclose personal information that we collect, or you provide:
        </p>
        <ul style={{ marginBottom: '15px', listStyleType: 'disc', paddingLeft: '20px' }}>
          <li style={{ marginBottom: '10px' }}>Disclosure for Law Enforcement: Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities</li>
          <li style={{ marginBottom: '10px' }}>Business Transaction: If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</li>
          <li style={{ marginBottom: '10px' }}>Other cases. We may disclose your information also: to contractors, service providers, and other third parties we use to support our business</li>
        </ul>

        <p style={{ marginBottom: '15px', lineHeight: '2' }}>
          <span style={{ fontWeight: 'bold', textDecoration: 'underline' }}>9. Security of Data</span>
          <br />
          The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
        </p>

        <p style={{ marginBottom: '15px', lineHeight: '2' }}>
          <span style={{ fontWeight: 'bold', textDecoration: 'underline' }}>10. Your Data Protection Rights Under General Data Protection Regulation (GDPR)</span>
          <br />
          If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR.
          <br />We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
          <br />
          If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at info@makethatmeme.com.
          <br />
          In certain circumstances, you have the following data protection rights:
        </p>
        <ul style={{ marginBottom: '15px', listStyleType: 'disc', paddingLeft: '20px' }}>
          <li style={{ marginBottom: '10px' }}>the right to access, update or to delete the information we have on you;</li>
          <li style={{ marginBottom: '10px' }}>the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;</li>
          <li style={{ marginBottom: '10px' }}>the right to object. You have the right to object to our processing of your Personal Data;</li>
          <li style={{ marginBottom: '10px' }}>the right of restriction. You have the right to request that we restrict the processing of your personal information;</li>
          <li style={{ marginBottom: '10px' }}>the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;</li>
          <li style={{ marginBottom: '10px' }}>the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;</li>
        </ul>

        <p style={{ marginBottom: '15px', lineHeight: '2' }}>
          Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.
          <br />
          You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
        </p>

        <p style={{ marginBottom: '15px', lineHeight: '2' }}>
          <span style={{ fontWeight: 'bold', textDecoration: 'underline' }}>11. Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)</span>
          <br />
          CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law’s reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy.
          <br />
          According to CalOPPA we agree to the following:
        </p>
        <ul style={{ marginBottom: '15px', listStyleType: 'disc', paddingLeft: '20px' }}>
          <li style={{ marginBottom: '10px' }}>users can visit our site anonymously;</li>
          <li style={{ marginBottom: '10px' }}>our Privacy Policy link includes the word “Privacy”, and can easily be found on the page specified above on the home page of our website;</li>
          <li style={{ marginBottom: '10px' }}>users will be notified of any privacy policy changes on our Privacy Policy Page;</li>
          <li style={{ marginBottom: '10px' }}>users are able to change their personal information by emailing us at info@makethatmeme.com.</li>
        </ul>

        <p style={{ marginBottom: '15px', lineHeight: '2' }}>
          <span style={{ fontWeight: 'bold', textDecoration: 'underline' }}>12. Service Providers</span>
          <br />
          We may employ third party companies and individuals to facilitate our Service (“Service Providers”), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.
          <br />
          These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
          <br />
          The following third party services are required for this app to work properly:
        </p>
        <ul style={{ marginBottom: '15px', listStyleType: 'disc', paddingLeft: '20px' }}>
          <li style={{ marginBottom: '10px' }}>Supabase, to handle user authentication and data storage</li>
          <li style={{ marginBottom: '10px' }}>Stripe, to handle payments and subscriptions</li>
          <li style={{ marginBottom: '10px' }}>Postmark, to send emails</li>
        </ul>

        <p style={{ marginBottom: '15px', lineHeight: '2' }}>
          <span style={{ fontWeight: 'bold', textDecoration: 'underline' }}>13. Links to other sites</span>
          <br />
          Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
          <br />
          We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
        </p>

        <p style={{ marginBottom: '15px', lineHeight: '2' }}>
          <span style={{ fontWeight: 'bold', textDecoration: 'underline' }}>14. Children's privacy</span>
          <br />
          Our Services are not intended for use by children under the age of 13 (“Children”).
          <br />
          We do not knowingly collect personally identifiable information from Children under 13. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
        </p>

        <p style={{ marginBottom: '15px', lineHeight: '2' }}>
          <span style={{ fontWeight: 'bold', textDecoration: 'underline' }}>15. Changes to This Privacy Policy</span>
          <br />
          We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
          <br />
          We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.
          <br />
          You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
        </p>

        <p style={{ marginBottom: '15px', lineHeight: '2' }}>
          <span style={{ fontWeight: 'bold', textDecoration: 'underline' }}>16. Contact us</span>
          <br />
          If you have any questions about this Privacy Policy, please contact us by email: info@makethatmeme.com
        </p>
      </main>
    </div>
  );
};

export default Privacy;
